In [2]:
import pandas as pd

In [4]:
# Reading the csv file

df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Selecting one column
---

## Syntax 1

In [5]:
# Select a column with [] (Preferred way to select a column)

df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [6]:
# Check out the data type of a column

type(df_exams['gender'])

pandas.core.series.Series

In [14]:
# Series : attributes and methods

df_exams['gender'].index # RangeIndex(start=0, stop=1000, step=1)
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

## Syntax 2

In [19]:
# Select a column with dot '.'

df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [16]:
# Select a column with dot '.'  (pitfalls)

df_exams.math score

SyntaxError: invalid syntax (3540985961.py, line 3)

In [17]:
# Select the same column using []

df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

# Selecting two or more columns

In [20]:
# Select two columns using [[]]

df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [21]:
# Check out the data type of the selection

type(df_exams[['gender', 'math score']])

pandas.core.frame.DataFrame

In [22]:
# Select 2 or more columns using [[]]

df_exams[['gender', 'writing score', 'math score', 'reading score', ]]

     gender  writing score  math score  reading score
0    female             74          72             72
1    female             88          69             90
2    female             93          90             95
3      male             44          47             57
4      male             75          76             78
..      ...            ...         ...            ...
995  female             95          88             99
996    male             55          62             55
997  female             65          59             71
998  female             77          68             78
999  female             86          77             86

[1000 rows x 4 columns]

In [23]:
# We can't select 2 or more columns with "."

df_exams.'gender', 'math score'

SyntaxError: invalid syntax (281242850.py, line 3)

# Adding a new column

## Adding a new column with a scalar value

In [25]:
# Adding a new column to dataframe

df_exams['language score'] = 70 
df_exams # All the rows will have same value (70).

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

## Adding a new column with an array

The dataframe has 1000 rows, so we need to create an array with 1000 elements.

In [26]:
# Import numpy

import numpy as np

In [27]:
# Create an array of 1000 elements

language_score = np.arange(0, 1000) 
# np.arange(0, 1000) is used to create an array which has 1000
# elements, from 0 to 999.

In [28]:
# Length of the array

len(language_score)

1000

In [29]:
# Adding a new column to dataframe with an array

df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [30]:
# Create random integer numbers between 1 and 100

int_language_score = np.random.randint(1, 100, size = 1000)

In [32]:
# Min value inclusive and high value exclusive

min(int_language_score)
max(int_language_score)

np.int32(99)

In [33]:
# Adding a new column to dataframe with an array

df_exams['language score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,8
1,female,group C,some college,standard,completed,69,90,88,7
2,female,group B,master's degree,standard,none,90,95,93,60
3,male,group A,associate's degree,free/reduced,none,47,57,44,8
4,male,group C,some college,standard,none,76,78,75,82
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,44
996,male,group C,high school,free/reduced,none,62,55,55,11
997,female,group C,high school,free/reduced,completed,59,71,65,60
998,female,group D,some college,standard,completed,68,78,77,14
999,female,group D,some college,free/reduced,none,77,86,86,19

In [37]:
# Create random float number between 1 and 100

float_array = np.random.uniform(1, 100, size = 100)

## assign()

When to use assign?
- Add multiple columns in a single line of code
- When you need to overwrite the value of an existing columns (best practice)

It returns a new object (a copy) with all the original columns in addition to the new ones.

In [39]:
# Create random numbers for our new score columns

score1 = np.random.randint(1, 100, size = 1000)
score2 = np.random.randint(1, 100, size = 1000)

In [42]:
# Create a series using the random numbers

series1 = pd.Series(score1, index = np.arange(0, 1000))
series2 = pd.Series(score2, index = np.arange(0, 1000))

In [44]:
# Using assign() to add multiple columns

df_exams.assign(score1 = series1, score2 = series2) # Creates a copy
df_exams = df_exams.assign(score1 = series1, score2 = series2)

In [45]:
# Show dataframe

df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,8,60,85
1,female,group C,some college,standard,completed,69,90,88,7,71,93
2,female,group B,master's degree,standard,none,90,95,93,60,84,73
3,male,group A,associate's degree,free/reduced,none,47,57,44,8,83,64
4,male,group C,some college,standard,none,76,78,75,82,91,87
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,44,17,60
996,male,group C,high school,free/reduced,none,62,55,55,11,49,2
997,female,group C,high school,free/reduced,completed,59,71,65,60,84,84
998,female,group D,some college,standard,completed,68,78,77,14,65,98
999,female,group D,some college,free/reduced,none,77,86,86,19,5,34

## insert()

Inserts a new column at a specfic position or index.

In [46]:
# Using index() to add a column at a specific position or index.

df_exams.insert(1, 'test', series1)
# (index of column, name of column, array of values to be inserted)

In [47]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,60,group B,bachelor's degree,standard,none,72,72,74,8,60,85
1,female,71,group C,some college,standard,completed,69,90,88,7,71,93
2,female,84,group B,master's degree,standard,none,90,95,93,60,84,73
3,male,83,group A,associate's degree,free/reduced,none,47,57,44,8,83,64
4,male,91,group C,some college,standard,none,76,78,75,82,91,87
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,17,group E,master's degree,standard,completed,88,99,95,44,17,60
996,male,49,group C,high school,free/reduced,none,62,55,55,11,49,2
997,female,84,group C,high school,free/reduced,completed,59,71,65,60,84,84
998,female,65,group D,some college,standard,completed,68,78,77,14,65,98
999,female,5,group D,some college,free/reduced,none,77,86,86,19,5,34