In [3]:
import pandas as pd
import numpy as np

In [4]:
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# Math Operations

## Operations in columns

In [5]:
# Select a column and calculate total sum

df_exams['math score'].sum()

np.int64(66089)

In [6]:
# count, mean, std, max and min

df_exams['math score'].count()
df_exams['math score'].mean()
df_exams['math score'].std()  # Standard deviation
df_exams['math score'].max()
df_exams['math score'].min()

0

In [7]:
# Easier calculation with .describe()

df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

## Operations in Rows

In [10]:
# Calculating the sum in row

df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [11]:
# Calculating the average score and assigning the result to a 
# new column

df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [14]:
# Showing the dataframe

df_exams.round(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,72.67
1,female,group C,some college,standard,completed,69,90,88,82.33
2,female,group B,master's degree,standard,none,90,95,93,92.67
3,male,group A,associate's degree,free/reduced,none,47,57,44,49.33
4,male,group C,some college,standard,none,76,78,75,76.33
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,94.00
996,male,group C,high school,free/reduced,none,62,55,55,57.33
997,female,group C,high school,free/reduced,completed,59,71,65,65.00
998,female,group D,some college,standard,completed,68,78,77,74.33
999,female,group D,some college,free/reduced,none,77,86,86,83.00

## Value Counts

In [15]:
# Counting gender elements

# len function
len(df_exams['gender'])

# .count() method
df_exams['gender'].count()

np.int64(1000)

In [17]:
# Counting gender elements by category

df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [18]:
# Return the relative frequency (divide all values by 
# the sum of values)

df_exams['gender'].value_counts(normalize = True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [20]:
# Counting 'parental level of education' element by category

df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [22]:
# Return the relative frequency and round to 2 decimals

df_exams['parental level of education'].value_counts(normalize = True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

## Sort a Dataframe

In [23]:
# Sort by one column

df_exams.sort_values(by = 'math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
787,female,group B,some college,standard,none,19,38,32,29.666667
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
...,...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99,98.666667
623,male,group A,some college,standard,completed,100,96,86,94.000000
451,female,group E,some college,standard,none,100,92,97,96.333333
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667

In [24]:
# Sort descending by one column

df_exams.sort_values('math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
623,male,group A,some college,standard,completed,100,96,86,94.000000
451,female,group E,some college,standard,none,100,92,97,96.333333
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [26]:
# Sort descending by multiple columns

# df_exams.sort_values(['math score', 'reading score'], 
                    # ascending = False) # works in same manner
df_exams.sort_values(by = ['math score', 'reading score'], 
                    ascending = False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [29]:
# Sort descending bu multiple columns and update dataframe

df_exams.sort_values(['math score', 'reading score'], 
                     ascending = False,
                     inplace = True)

In [30]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000
962,female,group E,associate's degree,standard,none,100,100,100,100.000000
625,male,group D,some college,standard,completed,100,97,99,98.666667
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333
787,female,group B,some college,standard,none,19,38,32,29.666667
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000
980,female,group B,high school,free/reduced,none,8,24,23,18.333333
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000

In [31]:
# Sort descending with a key function
# We'll use the 'key' argument to ignore case of text
df_exams.sort_values('race/ethnicity', ascending=True, 
                     key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average
741,female,group A,associate's degree,free/reduced,none,37,57,56,50.000000
151,male,group A,bachelor's degree,standard,none,77,67,68,70.666667
811,male,group A,high school,free/reduced,none,45,47,49,47.000000
112,male,group A,associate's degree,standard,none,54,53,47,51.333333
25,male,group A,master's degree,free/reduced,none,73,74,72,73.000000
...,...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65,68.333333
915,female,group E,some college,standard,none,68,70,66,68.000000
592,male,group E,bachelor's degree,standard,none,68,68,64,66.666667
479,male,group E,associate's degree,standard,none,76,71,67,71.333333
517,female,group E,some college,standard,completed,66,74,73,71.000000

## Create Index

In [32]:
# Creating non repetitive values for the index

new_index = np.arange(0, 1000)

In [34]:
# Shuffling the indexes

import random
random.shuffle(new_index)

In [36]:
# Create a new column with new index

df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,average,new_index
149,male,group E,associate's degree,free/reduced,completed,100,100,93,97.666667,486
458,female,group E,bachelor's degree,standard,none,100,100,100,100.000000,860
916,male,group E,bachelor's degree,standard,completed,100,100,100,100.000000,896
962,female,group E,associate's degree,standard,none,100,100,100,100.000000,968
625,male,group D,some college,standard,completed,100,97,99,98.666667,906
...,...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,31.333333,372
787,female,group B,some college,standard,none,19,38,32,29.666667,571
17,female,group B,some high school,free/reduced,none,18,32,28,26.000000,579
980,female,group B,high school,free/reduced,none,8,24,23,18.333333,348
59,female,group C,some high school,free/reduced,none,0,17,10,9.000000,939

## Set Index

In [38]:
# Set new_index column as index

df_exams.set_index('new_index', inplace=True)

## Sort Index

In [55]:
# Sort dataframe by new index

df_exams.sort_index(ascending=True, inplace=True)

# Rename Column

In [43]:
# Rename column and overwrite values of the dataframe

df_exams = df_exams.rename(columns={'gender' : 'Gender'})

In [44]:
# Rename multiple columns and update the dataframe with 
# inplace arguement

df_exams.rename(columns={'math score' : 'MS',
                         'reading score' : 'RS',
                         'writing score' : 'WS'}, inplace=True)

In [45]:
# Show dataframe

df_exams

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,average
new_index,,,,,,,,,
999,male,group C,some college,standard,none,69,64,68,67.000000
998,male,group C,high school,standard,none,70,70,65,68.333333
997,female,group E,some college,standard,none,62,73,70,68.333333
996,female,group C,high school,standard,none,72,80,83,78.333333
995,female,group B,associate's degree,free/reduced,completed,68,77,80,75.000000
...,...,...,...,...,...,...,...,...,...
4,male,group C,some college,free/reduced,none,63,61,54,59.333333
3,male,group D,some high school,standard,none,73,66,62,67.000000
2,male,group E,some high school,free/reduced,completed,73,67,59,66.333333
1,male,group A,bachelor's degree,standard,completed,80,78,81,79.666667
0,male,group E,some college,standard,completed,81,74,71,75.333333

## Rename Index

In [56]:
# Rename index 0, 1 and 2 and update the dataframe

df_exams.rename(index={0:'A',
                       1:'B',
                       2:'C'}, inplace=True)

In [57]:
# Show first 3 rows

df_exams.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,average
new_index,,,,,,,,,
A,male,group E,some college,standard,completed,81,74,71,75.333333
B,male,group A,bachelor's degree,standard,completed,80,78,81,79.666667
C,male,group E,some high school,free/reduced,completed,73,67,59,66.333333